### ISSUE TITLE
Getting StopIteration: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ninjakx** [experiencor/keras-yolo3#17]
```
count 	[44][5]
loss: 	[44][57.3060036]
loss: 	[44][173.999207]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/content/drive/keras-yolo3/generator.py", line 73, in __getitem__
    img, all_objs = self._aug_image(train_instance, net_h, net_w)
  File "/content/drive/keras-yolo3/generator.py", line 160, in _aug_image
    image = cv2.imread(image_name)[:,:,::-1] # RGB image
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 251, in <module>
    _main_(args)
  File "train.py", line 210, in _main_
    max_queue_size   = 4
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: 'NoneType' object is not subscriptable
```

**Comment by experiencor** [comment]
That image is not found.

**Comment by ninjakx** [comment]
but i have all the images in the datasets.
https://drive.google.com/open?id=11nlaCN6zR8r_xAiv49hHEjUymyQPsuxO

**Comment by experiencor** [comment]
@ninjakx @Sun-Wu-kon Try running the latest code. It will print the path to the image it fails to find.

**Comment by Sun-Wu-kon** [comment]
@experiencor Thank you! I'v solved it.There is something wrong with raccoon dataset.It is very strange,when i download it from https://github.com/datitran/raccoon_dataset ,the .xml file in annotation its filename become .png from .jpg (like raccoon-1.jpg to raccoon-1.png).

**Comment by ninjakx** [comment]
@Sun-Wu-kon  yeah it's filename gets changed. But even after  having the images in png format it gave me an error .
Are you able to train the model ?

**Comment by ninjakx** [comment]
@experiencor I tried latest code too but weights doesn't get saved .It gives 'raccoon.h5' not found .
Previous code used to generate weights.

**Comment by experiencor** [comment]
you must complete an epoch for it to save the weight

**Comment by ninjakx** [comment]
But for that train.py should work . Running the train.py gives me 

`/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
valid_annot_folder not exists. Spliting the trainining set.
Seen labels: 		{'raccoon': 217}
Given labels: 		[u'raccoon']
Overlap labels: 	['raccoon']
[u'raccoon']
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    _main_(args)
  File "train.py", line 252, in _main_
    train_model.load_weights(config['train']['saved_weights_name'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2647, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'raccoon.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by experiencor** [comment]
it's a bug, I updated the code

**Comment by andreasmarxer** [comment]
I still have the TypeError: 'NoneType' error for line 164 in generator.py (image = image[:,:,::-1] # RGB image). The image is not missing and also the xml in the annotation is named correctly.

A bit weird is that the path of the missing files listed before the error is an old one - meaning not the one i have actually in my config file.

Anyone has the same issue or an idea?
![NoneType_Error](https://user-images.githubusercontent.com/45263298/65551930-4e2e0900-df23-11e9-90dc-bc40682a16e8.png)

**Comment by ameanprogrammer** [comment]
Hey @andreasmarxer were you able to find a fix? I'm running into the same issue right now.

**Comment by alimisumanth** [comment]
Hai even I faced this issue can anyone help me in solving this error.

**Comment by andreasmarxer** [comment]
I think in my case the issue came from versions that are not specified.
As far as I remember it worked with keras 2.2.4, tensorflow-gpu 1.12.0 and python 3.6.4.
But I didn't keep on working with this implementation and switched to the original Darknet C.

**Comment by Rajasekhar06** [comment]
> I think in my case the issue came from versions that are not specified.
> As far as I remember it worked with keras 2.2.4, tensorflow-gpu 1.12.0 and python 3.6.4.
> But I didn't keep on working with this implementation and switched to the original Darknet C.

you Can also checkout [this](https://github.com/AlexeyAB/darknet) repo which is a fork of the Original Darknet repo


BTW I kept only XML files which have images and moves remaining XML's without images and deleted the cached files too which also carry the error I'll keep posting if any resolution found
